---
abstract: "Perl interface to Apple's Find My iPhone service"
author:
  - 'Mike Greb <michael@thegrebs.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.026
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-FindMyiPhone
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojolicious: 0
  perl: 5.010001
resources:
  bugtracker: https://github.com/mikegrb/WebService-FindMyiPhone/issues
  homepage: https://github.com/mikegrb/WebService-FindMyiPhone
  repository: https://github.com/mikegrb/WebService-FindMyiPhone.git
version: 0.01
x_contributors:
  - 'mikegrb <mgreb@linode.com>'
